version: "3"

services:
    user-emu:
        container_name: cve2020_29557
        build:
          context: .
          dockerfile: ./user-emu/Dockerfile
        privileged: true
        ports:
          - "8888:80"
